name: Build Velocity

on:
  push:
    branches: [ "main", "master", "dev" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'gradle'
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew build
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Velocity-Artifacts
          path: |
            proxy/build/libs/*.jar
            !proxy/build/libs/*-sources.jar
            !proxy/build/libs/*-javadoc.jar
            !proxy/build/libs/*-all.jar
          if-no-files-found: error

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            */build/test-results/test/
            */build/reports/tests/test/
          if-no-files-found: ignore
