# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build-11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build

    - name: Upload Velocity Proxy Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Velocity-Proxy
        path: proxy/build/libs/velocity-proxy-*.jar
        if-no-files-found: error

    - name: Upload API Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Velocity-API
        path: api/build/libs/velocity-api-*.jar
        if-no-files-found: error

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          proxy/build/libs/velocity-proxy-*.jar
          api/build/libs/velocity-api-*.jar
        draft: false
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
