name: Publish to Maven Local

on:
  workflow_dispatch:  # 允许手动触发
  push:
    branches: [ "main", "master", "dev", "new" ]
    paths:
      - 'api/**'
      - 'proxy/**'
      - 'native/**'
      - 'build.gradle'
      - 'settings.gradle'

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'gradle'
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Publish to Maven Local
        run: ./gradlew publishToMavenLocal --no-daemon
        
      - name: Upload Maven Local Repository
        uses: actions/upload-artifact@v3
        with:
          name: Maven-Local-Repository
          path: |
            ~/.m2/repository/com/velocitypowered/velocity-api/
            ~/.m2/repository/com/velocitypowered/velocity-proxy/
          if-no-files-found: error

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
